### ISSUE TITLE
SSL Certificate fails to verify

### ISSUE THREAD

**Issue by benhannel** [WohlSoft/libFreeImage#2]
```
Bens-MacBook-Pro-5:HW4 bhannel$ sudo imageio_download_bin freeimage
Ascertaining binaries for: freeimage.
Imageio: 'libfreeimage-3.16.0-osx10.6.dylib' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/imageio_download_bin", line 10, in <module>
    sys.exit(download_bin_main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/__main__.py", line 96, in download_bin_main
    download_bin(plugin_names=args.plugin, package_dir=args.package_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/__main__.py", line 62, in download_bin
    mod.download(directory=directory)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/plugins/_freeimage.py", line 70, in download
    get_remote_file(fname=fname, directory=directory, force_download=force_download)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/core/fetching.py", line 130, in get_remote_file
    _fetch_file(url, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/core/fetching.py", line 189, in _fetch_file
    % os.path.basename(file_name)
OSError: Unable to download 'libfreeimage-3.16.0-osx10.6.dylib'. Perhaps there is a no internet connection? If there is, please report this problem.
```

**Comment by Wohlstand** [comment]
Looks odd... Btw, this repo contains a fork of FreeImage that was made to be lite (I kept only BMP, GIF, PNG and ICO formats be supported here). The thing that is imageio_download_bin is probably takes one of old official FreeImage versions which is, as I see, broken. You have an option to take the source code of FreeImage and build it by yourself.
